ramsey:
  mw:
    host: "https://api.setminusx.com"
  client:
    url: ${ramsey.mw.host}/api/ramsey/clients
    registration:
      phone-home:
        frequency-in-millis: ${CLIENT_PHONE_HOME_FREQ:60000}
      timeout:
        frequency-in-millis: ${CLIENT_TIMEOUT_CHECK_FREQ:60000}
        threshold-in-minutes: ${CLIENT_TIMEOUT_THRESHOLD:5}

  graph:
    url: ${ramsey.mw.host}/api/ramsey/graphs
  work-unit:
    queue:
      depth:
        min: ${WORK_UNIT_QUEUE_DEPTH_MIN:2500}
        max: ${WORK_UNIT_QUEUE_DEPTH_MAX:5000}
      url: ${ramsey.mw.host}/api/ramsey/work-units
      analysis-type: ${WORK_UNIT_ANALYSIS_TYPE:COMPREHENSIVE, TARGETED}
      frequency-in-millis: ${WORK_UNIT_QUEUE_FEEDER_FREQ:30000}
    assignment:
      count-per-client: ${WORK_UNIT_ASSIGNMENT_COUNT:500}
      frequency-in-millis: ${WORK_UNIT_ASSIGNMENT_FREQ:30000}