ramsey:
  client:
    registration:
      url: "http://localhost:8080/api/ramsey/clients"
      phone-home:
        frequency-in-millis: 15000
  graph:
    url: "http://localhost:8080/api/ramsey/graphs"
  work-unit:
    queue:
      depth:
        min: 1000
        max: 2000
      url: "http://localhost:8080/api/ramsey/work-units"
      frequency-in-millis: 10000
    assignment:
      count-per-client: 100
      frequency-in-millis: 10000