logging:
  level:
    root: INFO
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    console: "[%d{${logging.pattern.dateformat}}] %clr([%X{traceId:-},%X{spanId:-}]){blue} %clr(%5p){green} %clr(${PID:-}){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"


spring:
  main:
    web-application-type: none

ramsey:
  campaign-id: 1
  stage:
    top-results-count: ${TOP_RESULTS_COUNT:10}
    exhaustion-delay-ms: ${EXHAUSTION_DELAY_MS:60000}
    cycle-prevention-graph-lookback-count: ${CYCLE_PREVENTION_GRAPH_LOOKBACK_COUNT:50}