ramsey:
  mw:
    host: "http://ramsey-mw:8080"
  client:
    url: ${ramsey.mw.host}/api/ramsey/clients
    registration:
      phone-home:
        frequency-in-millis: ${CLIENT_PHONE_HOME_FREQ:60000}
      timeout:
        frequency-in-millis: ${CLIENT_TIMEOUT_CHECK_FREQ:60000}
        threshold-in-minutes: ${CLIENT_TIMEOUT_THRESHOLD:5}

  graph:
    url: ${ramsey.mw.host}/api/ramsey/graphs
  work-unit:
    queue:
      depth:
        min: ${WORK_UNIT_QUEUE_DEPTH_MIN:32000000}
        max: ${WORK_UNIT_QUEUE_DEPTH_MAX:64000000}
        publish-batch-size: ${WORK_UNIT_QUEUE_PUBLISH_COUNT:200000}
      url: ${ramsey.mw.host}/api/ramsey/work-units
      analysis-type: ${WORK_UNIT_ANALYSIS_TYPE:TARGETED} # COMPREHENSIVE, TARGETED
      frequency-in-millis: ${WORK_UNIT_QUEUE_FEEDER_FREQ:30000}
  campaign:
    url: ${ramsey.mw.host}/api/ramsey/campaigns
  stage:
    url: ${ramsey.mw.host}/api/ramsey/stages

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}